openapi: 3.1.0
info:
  title: Task Api
  version: 3.1.0
servers:
  - url: http://localhost:3000
tags:
  - name: Tasks
    description: Task-related endpoints
paths:
  /tasks:
    $ref: paths/tasks.yaml
